AllCops:
  Includes:
    - '**/*.rake'
    - 'Gemfile'
    - 'Gemfile.devtools'
  Excludes:
    - '**/vendor/**'
    - '**/benchmarks/**'

# Avoid parameter lists longer than five parameters.
ParameterLists:
  Max: 3
  CountKeywordArgs: true
  Enabled: false

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 3

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect:  'map'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'

# Limit line length
LineLength:
  Max: 79

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# Do not favor modifier if/unless usage when you have a single-line body
IfUnlessModifier:
  Enabled: false

# Allow case equality operator (in limited use within the specs)
CaseEquality:
  Enabled: false

# Constants do not always have to use SCREAMING_SNAKE_CASE
ConstantName:
  Enabled: false

# Not all trivial readers/writers can be defined with attr_* methods
TrivialAccessors:
  Enabled: false

SignalException:
  # Valid values are: semantic, only_raise and only_fail
  EnforcedStyle: only_raise
